!!es.um.poa.agents.seller.SellerAgentConfig
lotes:
  - kg: 10.0
    tipo: "sardina"
    precioReserva: 100.0
    precioSalida: 200.0
    precioActual: 200.0
  - kg: 6.0
    tipo: "boqueron"
    precioReserva: 10.0
    precioSalida: 20.0
    precioActual: 20.0